Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%config InlineBackend.figure_format = 'jpg'
import h5py
from lightguide import filters
import numpy as np
import matplotlib.pyplot as plt


data = h5py.File('/home/marius/Downloads/trace_POPO.PC1PC6..SHZSHZ.h5')

data.keys()
corrs = data['corr_data']
first_tr = corrs[tuple(corrs.keys())[0]]

ntraces = len(corrs)
nsamples = first_tr.size


corr_data = np.zeros((ntraces, nsamples))

for itr, data in enumerate(corrs.values()):
    corr_data[itr] = data

corr_data = corr_data.astype(np.float32)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mconfig[39m[38;5;124m'[39m, [38;5;124m"[39m[38;5;124mInlineBackend.figure_format = [39m[38;5;124m'[39m[38;5;124mjpg[39m[38;5;124m'[39m[38;5;124m"[39m)
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mh5py[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlightguide[39;00m [38;5;28;01mimport[39;00m filters
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[0;31mModuleNotFoundError[0m: No module named 'h5py'
ModuleNotFoundError: No module named 'h5py'

